#!/bin/sh

if [ "$reason" != BOUND ] && [ "$reason" != RENEW ] \
   && [ "$reason" != REBIND ] && [ "$reason" != REBOOT ]
then
        return
fi

if [ ! -z $new_host_name ] ; then
    hn="$new_host_name"
    [ ! -z $new_domain_name ] && hn="$hn.$new_domain_name"

    # update the hostname
    echo $hn > /etc/hostname
    hostname $hn

    # restart syslog to use the correct hostname.
    invoke-rc.d syslog-ng restart
fi
