#!/bin/sh

if [ "$reason" != BOUND ] && [ "$reason" != RENEW ] \
   && [ "$reason" != REBIND ] && [ "$reason" != REBOOT ]
then
        return
fi

hostname=$(host $new_ip_address | cut -d ' ' -f 5)
hostname=${hostname%*.}
echo $hostname > /etc/hostname

# update the hostname
hostname $hostname

# restart syslog to use the correct hostname.
invoke-rc.d syslog-ng restart
