#!/bin/bash

set -e

. /lib/libduck.sh

cat - <<ENDL
               _              
            .-' '-.           
          .'       '.         
         :-._o) (o_.-:        
        (    /   \    )       
         '-.'     '.-'        
           '.   .'            
             i\ /i            
       .    :  '  :    .      
        "\. :     : ./"       
          \\|     |//         
         .' :     : '.        
      .-'  :       :  '-.     
     : i .'         '. i :    
    :   :             :   :   
    :  .'             '.  :   
     :/                 \:    
      '.               .'     
        '-._________.-'       
                              
      | You are Ducked! |     

ENDL

timeout_with 3 "Installation starting in..."
