#!/bin/sh
. /lib/libduck.sh

if [ "$DUCK_MODE" = "testing" ]; then
    warning "Skipping network configuration, duck/mode=testing"
    exit 0
fi

info "network: Setting up loopback interface"

info "network: lo: address"
ip addr add 127.0.0.1/8 dev lo || true
info "network: lo: route"
ip route add 127.0.0.0/8 dev lo || true
info "network: lo: link up"
ip link set lo up

info "network: eth0: Configuring using dhcp"

if ! dhclient eth0; then
    error "Network setup failed"
    exit 1
fi

info "network: eth0: link up"

# Set hostname from DHCP
a_set hostname $(hostname)

exit 0
