#!/bin/bash

set -e

. /lib/libduck.sh

info "duckdb: Loading Variables"

if [[ -f $DUCKDB_CONF ]]; then
  info "duckdb: loading $DUCKDB_CONF"
  duckdb file $DUCKDB_CONF
fi

info "duckdb: loading /proc/cmdline"
if ! duckdb cmdline /proc/cmdline; then
    error "duckdb: Failed to load kernel arguments"
    exit 1
fi

exit 0
