#!/bin/bash

set -e

. /lib/libduck.sh

if [[ "$DUCK_MODE" == "testing" ]]; then
    warning "Skipping network configuration, duck/mode=testing"
    exit 0
fi

info "Setting up network with dhcp"

if ! dhclient eth0; then
    error "Network setup failed"
    exit 1
fi

exit 0
