#!/bin/bash
. /lib/libduck.sh
a_get_into target duck/target
a_get_into suite debootstrap/suite
a_get_into mirror debootstrap/mirror

if [[ ! -d $target ]]; then
    error "Target does not exist: $target"
    exit 1
fi

debootstrap $suite $target $mirror

mount --bind /dev $target/dev
mount -t proc none $target/proc
mount -t sysfs none $target/sys
