#!/bin/bash

set -e

. /lib/libduck.sh

a_get duck/target
target="$RET"

a_get debootstrap/suite
suite="$RET"

a_get debootstrap/mirror
mirror="$RET"

if [[ ! -d $target ]]; then
    error "Target does not exist: $target"
    exit 1
fi

debootstrap $suite $target $mirror

mount --bind /dev $target/dev
mount -t proc none $target/proc
mount -t sysfs none $target/sys
