#!/bin/sh
. /lib/libduck.sh
a_get_into reboot_enabled "reboot/enabled" "True"

if [ "$DUCK_MODE" = "testing" ]; then
    warning "Not rebooting, duck/mode=testing"
    exit 0
fi

info "Installation done, rebooting!"

if [ "$reboot_enabled" = "True" ]; then
    reboot
else
    info "Not rebooting, reboot/enabled=$reboot_enabled"
fi

exit 0
