#!/bin/sh
# Make busybox applets available in the PATH for general use

set -e

case "$1" in
    "post-packages-configure")
        for a in $(/bin/busybox --list) ; do
            which $a >/dev/null || ln -s busybox /bin/$a
        done
        ;;
esac

exit 0
