#!/bin/bash
# Remove any persistent udev rules
# If the host system runs it's own udev daemon, there is a chance that installation
# hooks will trigger the generation of persistent files.

set -e

case "$1" in
  "final") rm -f /etc/udev/rules.d/*; ;;
esac
