#!/bin/bash
# Make sure that the kernel does not generate an initramfs.
# Clear /boot before packages are being configured.

set -e

status_code=0

case "$1" in
    "pre-packages-configure")
        echo "Disabling generation of an initramfs"

        rm -rf /etc/kernel/postinst.d
        rm -rf /etc/kernel/postrm.d

        dpkg --get-selections | while read name _; do
            case "$name" in
                linux-image-*-dbg) continue ;;
                linux-image-*)  ;;
                *) continue ;;
            esac

            version=${name#linux-image-*}

            path="/var/lib/dpkg/info/$name.postinst"

            [[ ! -f $path ]] && continue

            if ! grep -E 'my \$initrd\s+=\s+"YES";' $path; then
                echo "initrd already disabled: $name"
                continue
            fi

            cp -a $path $path.original

            echo "Disabling initrd for: $name"

            if ! sed -r -i 's/my \$initrd\s+=\s+"YES";/my $initrd = "";/' $path; then
                echo "failed to patch: $path"
                exit 1
            fi

            echo "Generating modules.dep"
            depmod $version
        done
        ;;
    "final")
        echo "Clearing /boot"
        rm -rf /boot
        ;;
esac

exit 0
