#!/bin/sh
# fix for dash hooks that does not run properly on it's own.
# http://wiki.debian.org/Multistrap#Steps_for_Squeeze_and_later

set -e

case "$1" in
    "pre-bootstrap-configure")
        mkdir -p /usr/share/man/man1
        ;;
    *) ;;
esac

exit 0
