#!/bin/bash

. /lib/libduck.sh

info "Duck Installer $DUCK_VERSION"

a_get duck/log "$DEFAULT_LOG"
log="$RET"

if [[ -f $INSTALLER_STATUS ]]; then
    info "Not running installation, $INSTALLER_STATUS exists"
    exec $DUCK_LOGIN
fi

info "Running installation, logging to $log and syslog"
run_installer 2>&1 tee -a $log | logger -s -t duckinstall

touch $INSTALLER_STATUS

exec $DUCK_LOGIN
