#!/bin/bash

. /lib/libduck.sh

info "Duck Installer $DUCK_VERSION"

a_get duck/log "$DEFAULT_LOG"
log="$RET"

if [[ -f $INSTALLER_STATUS ]]; then
    info "Not running installation, $INSTALLER_STATUS exists"
else
    info "Running installation, logging to $log"
    run_installer | tee -a $log
    touch $INSTALLER_STATUS
fi

exec /sbin/ducklogin
