#!/bin/bash
. /lib/libduck.sh
a_get_into log duck/log "$DEFAULT_LOG"
a_get_into error_command 'duck/error-command' "$DUCK_LOGIN"
a_get_into success_command 'duck/success-command' "$DUCK_LOGIN"

trap $error_command INT TERM

info "Duck Installer $DUCK_VERSION"

if [[ -f $INSTALLER_STATUS ]]; then
    info "Not running installation, $INSTALLER_STATUS exists"
    exec $DUCK_LOGIN
fi

info "Running installation, logging to $log and syslog"

if ! run_installer 2>&1 | tee -a $log | logger -t duckinstall -s; then
    exec $error_command
fi

touch $INSTALLER_STATUS
exec $success_command
